### ISSUE TITLE
A question about eq5 and eq6

### ISSUE THREAD

**Issue by lianchengmingjue** [zhyever/SimIPU#1]
Thanks for your inspiring work.
I have some wonder about eq5 and eq6.
As far as I know, After eq5, f should be a tensor which is a global feature with shape (batchsize * 2048 * 1 * 1), how can you sample corresponding image features by projection location? After all, there's no spatial information in f anymore.
Or maybe you got features from a previous layer of ResNet?
Looking forward to your reply.

**Comment by zhyever** [comment]
Thanks for your attention to our work. 

Eq.5 formulated the process of the image feature extraction. In detail, the ResNet-50 will provide five-level feature maps, which can be denoted as c1, c2, c3, c4, c5 each with 64, 256, 512, 1024, 2048 dimensions. We only utilize the c5 as the global feature map. Notably, we do not use global pooling to get the feature with shape (bs, c, 1, 1). We use the 'global' to describe the large receptive fields. 

Furthermore, the PointNet will produce global features of downsampled points and the locations as well. So we can apply the camera matrix to project the downsampled points to the c5 feature map to construct the correspondences. Notably, here the features from both modalities will be global, so we can abandon the decoder as written in our paper.

I would be happy if the reply helps.

**Comment by lianchengmingjue** [comment]
Got it. Thanks for your quick reply!
