### ISSUE TITLE
Question about augmentation

### ISSUE THREAD

**Issue by sunnyHelen** [zhyever/SimIPU#7]
Hi, I'm a little confused about the data augmentation.
1. How did you set img_aug when img_moco=True? It seems that we need an 'img_pipeline' in 'simipu_kitti.py', right?
2. For 3D augmentation, it seems that it is done in this line. So the 3D augmentation is done based on the point features instead the raw points, right? If I want to try moco=True, how to set 3D augmentation? should I do this in the dataset building part?
https://github.com/zhyever/SimIPU/blob/5b346e392c161a5e9fdde09b1692656bc7cd3faf/project_cl/decorator/inter_intro_decorator_moco_better.py#L394

Looking forward to your reply. Many thanks.

**Comment by zhyever** [comment]
For moco, we follow the implementation of mmselfsup. Please remind we do not use mono in our image branches (no contrastive loss in intra-image), so we do not need `img_pipeline` in  `simipu_kitti`.

Yes, given the raw point cloud p. We use feature extractor f to get p_f, meanwhile, we can get p_f' with f and augmented point cloud p'. The p_f and p_f' are with location l_p and l_p'. When implementation, we adopt the same transformation on (p_f, l_p), which is what this line is doing.

**Comment by sunnyHelen** [comment]
Ok, got it. Thanks a lot.
